openapi: '3.0.0'
info:
  version: 1.0.0
  title: Animals
  license:
    name: MIT
security:
  - petstore_auth:
      - 'read:pets'
externalDocs:
  description: Find out more about our animals
  url: https://example.com/more-info
paths:
  /animals:
    parameters:
      - name: limit
        in: query
        description: The path item level limit parameter
        required: false
        schema:
          type: integer
          maximum: 100
          format: int32
      - name: tags
        in: query
        description: tags to filter by
        allowEmptyValue: true
        required: true
        style: form
        schema:
          type: array
          items:
            type: string
    get:
      summary: List all animals
      operationId: listAnimals
      description: |
        Returns all animals
      deprecated: true
      externalDocs:
        description: Find out more about our animals
        url: https://example.com/more-info
      tags:
        - animals
      parameters:
        - name: limit
          in: query
          description: How many animals to return at one time (max 100)
          deprecated: true
          schema:
            type: integer
            maximum: 50
            format: int32
            nullable: true
        - name: offset
          in: header
          description: The number of animals to skip before starting to collect the result set
          required: false
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: A paged array of animals
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Animals'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      summary: Create an animal
      description: Creates a new animal
      operationId: addAnimal
      tags:
        - animals
      parameters:
        - name: authorization
          in: header
          description: The authorization token
          required: true
      requestBody:
        description: Animal to add
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Animal'
      security:
        - {}
        - petstore_auth:
            - 'write:pets'
            - 'read:pets'
        - api_key: []
      responses:
        '200':
          description: animal response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Animal'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /cats:
    get:
      summary: List all cats
      operationId: listCats
      tags:
        - animals
      responses:
        '200':
          description: A paged array of cats
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Animals'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /birds:
    get:
      summary: List all birds
      operationId: listBirds
      tags:
        - animals
      parameters:
        - name: limit
          in: query
          description: How many birds to return at one time (max 100)
          schema:
            type: integer
            example: 10
          example: 20
      responses:
        '200':
          description: A paged array of cats
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Animals'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /dogs:
    get:
      summary: List all dogs
      operationId: listDogs
      tags:
        - animals
      parameters:
        - name: limit
          in: query
          description: How many birds to return at one time (max 100)
          schema:
            type: integer
          example: 20
          examples:
            single:
              summary: A single dog
              description: A unique dog
              value: 1
              externalValue: 'https://example.com/dogs/1'
            multiple:
              value: 30
      responses:
        '200':
          description: A paged array of cats
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Animals'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /bears:
    get:
      summary: List all bears
      operationId: listBears
      tags:
        - animals
      parameters:
        - name: limit
          in: query
          description: How many birds to return at one time (max 100)
          content:
            application/json:
              schema:
                type: integer
              example: 20
            application/xml:
              schema:
                type: integer
              example: 30
      responses:
        '200':
          description: A paged array of cats
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Animals'
          headers:
            X-Rate-Limit-Limit:
              description: The number of allowed requests in the current period
              schema:
                type: integer
            X-Rate-Limit-Reset:
              description: The number of seconds left in the current period
              schema:
                type: integer
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Animal:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        tag:
          type: string
    Animals:
      type: array
      maxItems: 100
      items:
        $ref: '#/components/schemas/Animal'
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
